### ISSUE TITLE
大佬，有没有组件平移的方法？

### ISSUE THREAD

**Issue by Jdb156158** [Eilgnaw/ClockRotationEffect#1]
最近看到好多app实现了，图片滚动的效果，详细效果：https://discussionschinese.apple.com/thread/254963339

我的微信JDB118158168

有需要讨论这个问题的，大家可以加我一起讨论，或者在这个问题下讨论

**Comment by Eilgnaw** [comment]
https://github.com/Eilgnaw/WidgetAnimation
