### ISSUE TITLE
请问为什么小组件的旋转的anchor不生效呢

### ISSUE THREAD

**Issue by SunXia9288** [Eilgnaw/ClockRotationEffect#2]

**Comment by SunXia9288** [comment]
public init(period: ClockRotationEffect.ClockRotationPeriod, timezone: TimeZone, anchor: UnitPoint)

**Comment by SunXia9288** [comment]
当使用
 public init(period: ClockRotationEffect.ClockRotationPeriod, timezone: TimeZone, anchor: UnitPoint)
会导致 anchor 参数无效，无论设置什么锚点，都会从小组件中心视图开始作为旋转中心。
请问是不是使用方式有什么问题

**Comment by Eilgnaw** [comment]
这个不清楚.我只是简单的编译一下做个SPM包
